openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipies app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of recipes app
tags:
  - name: Recipies
    description: Operations about recipies.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000

paths:
  /recipes/{id}:
    get:
      $ref: ../swagger/paths/recipes/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/recipes/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/recipes/{id}/delete.yaml
  /recipes:
    get:
      $ref: '../swagger/paths/recipes/get.yaml'
    post:
      $ref: '../swagger/paths/recipes/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
