type: object
required:
  - title
  - category
  - instructions
  - description
  - ingredients

properties:
  _id:
    type: string
    description: Unique recipe ID
    example: '64a1b2c3e25d8c90e88d5678'

  title:
    type: string
    description: The full name of the recipe
    example: 'Breakfast Omelette'

  category:
    type: string
    description: The full name of the category
    enum:
      - Seafood
      - Lamb
      - Starter
      - Chicken
      - Beef
      - Dessert
      - Vegan
      - Pork
      - Vegetarian
      - Miscellaneous
      - Pasta
      - Breakfast
      - Side
      - Goat
      - Soup
    example: 'Breakfast'

  area:
    type: string
    description: The cuisine area (e.g. Italian, Mexican)
    example: 'Italian'

  instructions:
    type: string
    description: Preparation steps
    example: 'Crack the eggs and beat with a fork...'

  description:
    type: string
    description: Short description of the recipe
    example: 'A light and fluffy omelette perfect for breakfast.'

  thumb:
    type: string
    description: URL to recipe thumbnail image
    example: 'https://example.com/uploads/image.jpg'

  time:
    type: string
    description: Time needed to prepare the recipe
    example: '30 min'

  ingredients:
    type: array
    description: List of ingredients with their measures
    minItems: 1
    items:
      type: object
      required:
        - id
        - measure
      properties:
        id:
          type: string
          description: Ingredient ID
          example: '64a1b2c3e25d8c90e88d5678'
        measure:
          type: string
          description: Quantity and unit of the ingredient
          example: '2 tbsp'

  owner:
    type: string
    description: User ID who created the recipe
    example: '68419ace9cd45e2f9773af01'

  createdAt:
    type: string
    format: date-time
    description: Date of creation
    example: '2025-06-28T14:55:00Z'

  updatedAt:
    type: string
    format: date-time
    description: Last update date
    example: '2025-06-29T10:15:00Z'
